# -*- coding: utf-8 -*-
"""testing_iris_scikitlearn_petal.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wwgo8918xpzPIVmwyKaveYlKvL4EWQzO
"""

#For petal_length and Petal_width
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
import seaborn as sns 
from matplotlib import pyplot as plt 
from matplotlib import colors

irs = datasets.load_iris()
print ("Features: ", irs.feature_names) 
print ("Labels: ", irs.target_names)
print (irs.data[0:5])
print (irs.target)

X = irs.data[:, 2:] #slicing for petal_length and petal_width

# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, irs.target, test_size=0.3,random_state=109) 

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test) #
predicted = gnb.predict([[4,1]])
print ("Predicted =", predicted )

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
  
iris = sns.load_dataset('iris') 
  
# style used as a theme of graph  
# for example if we want black  
# graph with grid then write "blackgrid" 
sns.set_style("whitegrid") 
  
# sepal_length, petal_length are iris 
# feature data height used to define 
# Height of graph whereas hue store the 
# class of iris dataset. 
#sns.relplot(x="total_bill", y="tip", hue="smoker", style="time", data=X)
'''sns.FacetGrid(iris, hue ="species",
              height = 6).map(plt.scatter,  
                              'sepal_length',  
                              'sepal_width').add_legend()''' 


fig, ax = plt.subplots()
sns.relplot("petal_length", "petal_width",hue= "species",height=6, data=iris, ax = ax)

ax2 = ax.twinx()
sns.relplot(X_test[:, 0], X_test[:, 1], hue = y_pred, height=6, ax = ax2)
plt.show()

cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, square=True, annot=True, cmap='RdBu', cbar=False,
xticklabels=['Setosa', 'versicolour', 'virginica'], yticklabels=['Setosa', 'versicolour', 'virginica'])
plt.xlabel('true label')
plt.ylabel('predicted label')